    version: '3'
    services:
      redis-server:
        image: 'redis'
        networks: 
          - dockernetwork
        
      mongo-server:
        image: 'mongo'
        ports:
          -  '27017:27017'
        networks:
          - dockernetwork 
          
      jupyterhub-server:
        image: 'jupyterhub/jupyterhub'
        ports:
          -  '8000:8000'
        networks:
          - dockernetwork 
                   
      note-app:
        # restart: on-failure
        build: .
        ports:
          - '8081:8081'
          - '18888:8888'
         
        networks:
          - dockernetwork 
          
    networks:
      dockernetwork:
        external: true
         
